#!/usr/bin/env python

from hatohol import hatohol_def
import hashlib

def generate_one_user(name, password, flags):
    table_name = 'users'
    auto_increment_value = 0
    line = 'INSERT ' + table_name + ' VALUES ('
    line += '%d, \'%s\', \'%s\', %d);' % (auto_increment_value, name, password, flags)
    print line


def start():
    generate_one_user('admin', hashlib.sha256('hatohol').hexdigest(), hatohol_def.ALL_PRIVILEGES)
    generate_one_user('guest', hashlib.sha256('guest').hexdigest(), 0)


if __name__ == '__main__':
    start()
