((c-mode .   ((indent-tabs-mode . t)
              (c-basic-offset   . 8)))
 (c++-mode . ((indent-tabs-mode . t)
              (c-basic-offset   . 8)))
 (js-mode .  ((indent-tabs-mode . nil)
              (js-indent-level  . 2)))
 (sh-mode .  ((indent-tabs-mode . nil))))
