Document: hatohol
Title: Debian hatohol Manual
Author: <insert document author here>
Abstract: This manual describes what hatohol is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/hatohol/hatohol.sgml.gz

Format: postscript
Files: /usr/share/doc/hatohol/hatohol.ps.gz

Format: text
Files: /usr/share/doc/hatohol/hatohol.text.gz

Format: HTML
Index: /usr/share/doc/hatohol/html/index.html
Files: /usr/share/doc/hatohol/html/*.html
