#!/usr/bin/env python
import sys
import urllib2

DEFAULT_PORT = 33194

def print_usage():
  print "Usage: "
  print ""
  print "  $ hatohol-voyager [--server address[:port]] command [options]"
  print ""
  print "* commands"
  print ""
  print "  show-triggers"
  print "  show-events"
  print "  show-items"
  print "  show-actions"
  print ""

def parse_server_option(argv):
  if "--server" not in argv:
    return "http://localhost:%d" % DEFAULT_PORT
  idx = argv.index("--server")
  if idx == len(argv) - 1:
    print "--server: Not found server address"
    sys.exit(-1)
  
  server_arg = argv[idx + 1]
  words = server_arg.split(":")
  if len(words) >= 3:
    print "Invalid server option: " + server_arg
    sys.exit(-1)

  if len(words) == 1:
    server_name = server_arg
    port = DEFAULT_PORT
  else:
    server_name = words[0]
    port = int(words[1])
  
  print "Server: %s, port: %d" % (server_name, port)
  del argv[idx:idx+2]
  return "http://%s:%d" % (server_name, port)

def show_triggers(url, options):
  response = urllib2.urlopen(url + "/triggers.json")
  triggers_json = response.read()
  print triggers_json

def show_events(url, options):
  response = urllib2.urlopen(url + "/events.json")
  events_json = response.read()
  print events_json

def show_items(url, options):
  response = urllib2.urlopen(url + "/items.json")
  items_json = response.read()
  print items_json

def show_actions(url, options):
  response = urllib2.urlopen(url + "/actions.json")
  actions_json = response.read()
  print actions_json

command_map = {
  "show-events":show_events,
  "show-triggers":show_triggers,
  "show-items":show_items,
  "show-actions":show_actions,
}

#
# main
#
url = parse_server_option(sys.argv)

if len(sys.argv) < 2:
  print_usage()
  sys.exit(-1)

command = sys.argv[1]
if command not in command_map:
  print "The command: %s is unknown !!!" % command
  print ""
  sys.exit(-1)

command_map[command](url, sys.argv[2:])

